# Generated by Django 4.0.6 on 2022-08-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('banner_image', models.ImageField(upload_to='carousel')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
